### ISSUE TITLE
最新版本0.2.3在IOS上无法触发支付（失败）回调

### ISSUE THREAD

**Issue by fuxianwei** [0x5e/react-native-alipay#1]
react-native-alipay 0.2.2版本是正常的

**Comment by 0x5e** [comment]
0.2.3只是更新了支付宝iOS SDK，你测试使用的是正确的支付参数吗？我这边没有条件，用错误的支付参数测试，确实存在这问题

**Comment by fuxianwei** [comment]
参数是可以的，我0.2.2上使用一切是正常的，你试试用0.2.3在IOS下跳转支付然后取消看看能否收到正确的取消提示，目前我这边（0.2.3）是收不到用户正确取消的信息，但是0.2.2版本一切正常

**Comment by fuxianwei** [comment]
目前是IOS下面取消支付不能正确提示‘支付取消，请返回重新支付！’
这里是支付代码：
`
async pay() {
        try {
            let {cartInfo, orderType, resParams} = this.props.navigation.state.params
            let res = null, payResult = null

            this.setState({
                requesting: true
            })

            if(this.state.payType == 0) {
                res = await api.aliPay(resParams)
            } else if(this.state.payType == 1) {
                res = await api.weixinPay(resParams)
            }

            this.setState({
                requesting: false
            })

            if (res && res.data.status == 1) {
                if (orderType == 2) {
                    this.props.dispatch(ShopActions.cartRemoveShop(id))
                }

                if(this.state.payType == 0) {
                    payResult = await Alipay.pay(res.data.data)

                    if(payResult.resultStatus == 9000) {
                        this.props.navigation.dispatch({
                            type: 'ReplaceCurrentScreen',
                            routeName: "PayResult",
                            params: {res: 'ok', msg: `${cartInfo.totalPrice} 元`}
                        })
                    } else if(payResult.resultStatus == 6001) {
                        this.props.navigation.navigate('PayResult', {res: 'fail', msg: '支付取消，请返回重新支付！'})
                    } else {
                        this.props.navigation.navigate('PayResult', {res: 'fail', msg: '支付失败，请返回重新支付！'})
                    }
                } else if(this.state.payType == 1) {
                    let payParam = {
                        partnerId: res.data.data.partnerid,  // 商家向财付通申请的商家id
                        prepayId: res.data.data.prepayid,   // 预支付订单
                        nonceStr: res.data.data.noncestr,   // 随机串，防重发
                        timeStamp: res.data.data.timestamp.toString(),  // 时间戳，防重发
                        package: res.data.data.package,    // 商家根据财付通文档填写的数据和签名
                        sign: res.data.data.sign        // 商家根据微信开放平台文档对数据做的签名
                    }

                    payResult = await WeChat.pay(payParam)

                    if(payResult.type == 'PayReq.Resp') {
                        if(payResult.errCode == 0) {
                            this.props.navigation.dispatch({
                                type: 'ReplaceCurrentScreen',
                                routeName: "PayResult",
                                params: {res: 'ok', msg: `${cartInfo.totalPrice} 元`}
                            })
                        }
                    }
                }
            } else {
                Alert.alert(
                    '提示',
                    res.data.err_msg || '订单提交失败！',
                    [
                        {
                            text: '确定', onPress: () => {
                        }, style: 'cancel'
                        }
                    ],
                    {cancelable: false}
                )
            }
        } catch (e) {
            this.setState({
                requesting: false
            })
            if(e.name == 'WechatError') {
                if(e.code == -1) {
                    this.props.navigation.navigate('PayResult', {res: 'fail', msg: '支付失败，请返回重新支付！'})
                } else if(e.code == -2) {
                    this.props.navigation.navigate('PayResult', {res: 'fail', msg: '支付取消，请返回重新支付！'})
                }
            }
        }
    }
`

**Comment by woshizhoujie** [comment]
退回了0.2.2版本。。。

**Comment by fuxianwei** [comment]
目前只能回退版本了，等作者更新

**Comment by 0x5e** [comment]
我用支付宝demo试下来的情况是 Alipay iOS SDK v15.5.0 的`[AlipaySDK.defaultService payOrder:fromScheme:callback:]`回调没有执行，而v15.4.1是正常的。。。先回退吧，我再确认下如果确实是这问题的话，等官方修复了😅

**Comment by fuxianwei** [comment]
🙃哈哈只能这样了

**Comment by woshizhoujie** [comment]
![image](https://user-images.githubusercontent.com/24771453/33654739-fde6943a-daab-11e7-9992-ed12cd8b23e6.png)
求助

**Comment by 0x5e** [comment]
@woshizhoujie 还有别的编译错误一起出现吗？试试删除`node_modules/react-native/third-party`目录重新编译一下，看下这个：https://github.com/facebook/react-native/issues/14382

**Comment by django-wong** [comment]
+1

**Comment by dioxide** [comment]
sdk 升到15.5.3 实测支付能回调了@0x5e

**Comment by EvianZhow** [comment]
@0x5e Tested on Android and iOS latest Alipay App (10.1.22), and works fine. But you have to fix this issue first https://github.com/0x5e/react-native-alipay/issues/9

**Comment by EvianZhow** [comment]
@0x5e Now that #9 is closed, I think it's time to release the new version.

**Comment by 0x5e** [comment]
@EvianZhow Sure, thanks😄

**Comment by Micjoyce** [comment]
在最新版的 0.2.4 上，ios网页跳转支付完成之后，还是不会触发回调。

**Comment by Icacls** [comment]
试了0.2.4和0.2.2  都不能正确触发回调  代码如下：
async alipayLogin() {
    // 快捷登录授权
    try {
      // let infoStr = 'apiname=com.alipay.account.auth&method=alipay.open.auth.sdk.code.get&app_id=2018110662045033&app_name=mc&biz_type=openservice&pid=2088331067016317&product_id=APP_FAST_LOGIN&scope=kuaijie&target_id=xxxx&auth_type=AUTHACCOUNT&sign_type=RSA2&sign=xxxx'; // get from server, signed
      let response = await Alipay.authWithInfo(this.state.infoStr);
      console.info('alipayLogin------>', response);
      let { resultStatus, result, memo } = response;
      // let { success, result_code, auth_code, user_id } = QueryString.parse(result);

    } catch (error) {
      console.error(error);
    }
  }

另外native端iOS  openURL也没有触发。有人有遇到类似问题么

**Comment by Icacls** [comment]
试了0.2.4和0.2.2 都不能正确触发回调 代码如下：
```javascript
async alipayLogin() {
// 快捷登录授权
try {
let response = await Alipay.authWithInfo(this.state.infoStr);
console.info('alipayLogin------>', response);
let { resultStatus, result, memo } = response;
// let { success, result_code, auth_code, user_id } = QueryString.parse(result);

} catch (error) {
  console.error(error);
}
}
```
另外native端iOS openURL也没有触发。有人有遇到类似问题么

**Comment by 0x5e** [comment]
@Icacls 请试一下develop分支看看（0.2.5）

**Comment by Icacls** [comment]
develop分支（0.2.5）测试OK 👌多谢了！
