### ISSUE TITLE
element must be a direct child of the <application>

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [0x5e/react-native-alipay#13]
node_modules/@0x5e/react-native-alipay/android/src/main/AndroidManifest.xml:11: Error: The <activity> element must be a direct child of the <application> element [WrongManifestParent]
    <activity
    ^

   Explanation for issues of type "WrongManifestParent":
   The <uses-library> element should be defined as a direct child of the
   <application> tag, not the <manifest> tag or an <activity> tag. Similarly,
   a <uses-sdk> tag must be declared at the root level, and so on. This check
   looks for incorrect declaration locations in the manifest, and complains if
   an element is found in the wrong place.

   http://developer.android.com/guide/topics/manifest/manifest-intro.html

2 errors, 0 warnings

**Comment by gameboyVito** [comment]
Same issue, I'm using Gradle 4.6 with Android Studio 3.
