### ISSUE TITLE
 error: Build input file cannot be found: '/Users/xxx/app/node_modules/@0x5e/react-native-alipay/ios/libAlipaySDK.a'

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [0x5e/react-native-alipay#17]
error: Build input file cannot be found: '/Users/xxx/app/node_modules/@0x5e/react-native-alipay/ios/libAlipaySDK.a'

**Comment by alleniver** [comment]
same problem!

**Comment by 0x5e** [comment]
develop分支已更新，麻烦验证一下，谢谢～ @Darkhorse-Fraternity @alleniver
