### ISSUE TITLE
最新版本0.2.3，Android studio3.0.1上Gradle Sync异常

### ISSUE THREAD

**Issue by fuxianwei** [0x5e/react-native-alipay#2]
react-native：0.50.4
react-native-alipay：0.2.3

最新版Android Studio（3.0.1）上Gradle Sync失败
错误如下：
Error:Unable to find module with Gradle path ':@0x5e/react-native-alipay' (needed by module 'app'.)

**Comment by 0x5e** [comment]
我记得Android Studio 2.0是好的，可能和这个有关？ https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#variant_dependencies

暂时解决方法：将`android/settings.gradle`与`android/app/build.gradle`中出现的`@0x5e/react-native-alipay`改为`react-native-alipay`

猜测是`@`引起的问题

**Comment by fuxianwei** [comment]
这个已解决，谢谢
