### ISSUE TITLE
测试了一下Develop分支的组件，出现问题。（_OBJC_CLASS_$_UTDevice）

### ISSUE THREAD

**Issue by alleniver** [0x5e/react-native-alipay#20]
环境：
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 898.12 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.3.1

在清空node_modules和缓存后，运行React-Native run-ios会出现下面的错误：
Undefined symbols for architecture x86_64:

  "_OBJC_CLASS_$_UTDevice", referenced from:
      objc-class-ref in libRCTAlipay.a(libAlipaySDK.a)

ld: symbol(s) not found for architecture x86_64。

麻烦看看是哪里的问题！

**Comment by alleniver** [comment]
花了1-2个小时测试，始终都有这个错误，网上看了下说是支付宝的包引入错误。我现在退回到0.2.4了，你这个支付宝组件还是不错的，因为有一个微信的react-native-wechat有自带的支付功能，现在不缺那种集成支付宝+微信多种支付集成的，还是一个组件一个功能比较好用，容易整合和后期维护。

**Comment by 0x5e** [comment]
这是支付宝sdk在x64缺少某个类，可能这个sdk只能在真机上运行 @alleniver

**Comment by 0x5e** [comment]
查了解决方案都是说，用demo里的sdk就没这个问题，我再提交一下。。

**Comment by alleniver** [comment]
@0x5e 好的，你提交后我再看看！非常感谢。

**Comment by 0x5e** [comment]
@alleniver 周末提供😄

**Comment by alleniver** [comment]
good job man!

**Comment by alleniver** [comment]
测试过了可以正常使用了。谢谢老铁！
