### ISSUE TITLE
iOS AliPay.apy(str)闪退

### ISSUE THREAD

**Issue by GitXwj** [0x5e/react-native-alipay#48]
![Simulator Screen Shot - iPhone X - 2019-10-14 at 15 10 29](https://user-images.githubusercontent.com/20626405/66734220-cf2e4f80-ee94-11e9-9556-b4b4e5871313.png)

   const payStr =
          'app_id=2019101268290801' +
          '&method=alipay.trade.app.pay' +
          '&format=json' +
          '&charset=UTF-8' +
          '&sign_type=RSA2' +
          '&sign=APho46HqIR1P9rImcFBRsEjrZStIWzMrVQbS%2FMFhrLqvpwJsTdYRx3N87h78LzX8v8EwK%2FQgljhqhYIW3M8dcx73ceM4ViCmjBmlWcGQKx%2Bbw8a1Lv2tls2W881ZK80%2FyyxVr%2Bwg2zrMEKU5PpJENA7vqaT0IzNA0m1uuIA5l1m3A1Tr2gfCMo44OVWVUi9L1sJkQ26ByJVbnXEkckLmvaQxvp7PFMTV2gKH6RJUw%2FgIOWKAnfjKtAcqwNelbpBUSqJHu3yqqfzBKC%2FuYy1qJfaO%2BUAw1iPmobzcASAY8BVM2ObAQ6L915SJi%2FT8cu%2FVu%2FBesarvhFzV5cbu4G4%2FJw%3D%3D' +
          '&timestamp=2019-10-14+14%3A45%3A16' +
          '&version=1.0' +
          '&notify_url=http%3A%2F%2F192.168.1.19%2FappAlipay%2Fzfbpay' +
          '&biz_content=%7B%22out_trade_no%22%3A%2212019101414451581785043187954135%22%2C%22subject%22%3A%22%E6%B9%96%E5%8C%97%E7%A7%BB%E5%8A%A8%E8%AF%9D%E8%B4%B910%E5%85%83%E7%9B%B4%E5%85%85%22%2C%22timeout_express%22%3A%2230m%22%2C%22total_amount%22%3A%2210%22%7D';
        const result = await Alipay.pay(payStr);

**Comment by KaroseLiu** [comment]
我也遇到同样的issue，请问是怎么解决的呢~

**Comment by uniquker** [comment]
你好，怎么解决的

**Comment by uniquker** [comment]
找到问题了，是这个没有设置成功
Create a url type in Info -> URL Types. Set alipay to Identifier, set an unique id to URL Schemes (whatever you like).
