### ISSUE TITLE
 Alipay.setAlipaySandbox failed

### ISSUE THREAD

**Issue by yuanbolin** [0x5e/react-native-alipay#57]
Alipay.setAlipaySandbox is not function

**Comment by yuanbolin** [comment]
沙箱环境不能使用

**Comment by yuanbolin** [comment]
是因为新的支付宝demo里没有沙箱配置的原因吗

**Comment by DingChenyu** [comment]
这个试下 https://github.com/0x5e/react-native-alipay/issues/58

**Comment by yuanbolin** [comment]
万分感谢,已经询问蚂蚁金服解决了和你的一样

**Comment by 0x5e** [comment]
#40 已合入
