### ISSUE TITLE
Alipay.setAlipaySandbox(true) failed

### ISSUE THREAD

**Issue by DingChenyu** [0x5e/react-native-alipay#58]
_reactNativeAlipay.default.setAlipaySandbox is not a function

**Comment by DingChenyu** [comment]
已解决，需在node_modules>@0x5e>react-native-alipay>android>src>main>java>com>reactlibrary>AlipayModule.java file里：
**step1:**
 import com.alipay.sdk.app.EnvUtils  
**step2:** 
  @ReactMethod
  public void setAlipaySandbox(Boolean isSandbox) {
    if(isSandbox){
      EnvUtils.setEnv(EnvUtils.EnvEnum.SANDBOX);
    }else {
      EnvUtils.setEnv(EnvUtils.EnvEnum.ONLINE);
    }
  }

**Comment by 0x5e** [comment]
#40 已合入
