### ISSUE TITLE
rn0.61.4 ios 支付完成后不能自动跳转回到APP

### ISSUE THREAD

**Issue by tourze** [0x5e/react-native-alipay#60]
已经按照文档配置了，但是RN版本较新，不知道是否是RN版本问题。

**Comment by loveholly** [comment]
![image](https://user-images.githubusercontent.com/5133856/75305130-35e45200-5813-11ea-91bb-05a1a21b326f.png)

楼主配置这个了吗

**Comment by tourze** [comment]
> ![image](https://user-images.githubusercontent.com/5133856/75305130-35e45200-5813-11ea-91bb-05a1a21b326f.png)
> 
> 楼主配置这个了吗

![image](https://user-images.githubusercontent.com/13899502/75510190-1755a500-5a25-11ea-8c74-b234a18ca091.png)
有配置的。

**Comment by yunxu-it** [comment]
尝试一下在 `URL Schemes` 前面添加 `alipay`，如 `alipay****之前用的id****`

**Comment by wulaizi** [comment]
我也没返回 也添加了 URL types的

**Comment by CrystalLiu123** [comment]
在 URL Schemes 配置成 alipay2028xxxxx（支付宝给的appId）解决了我同样的问题
