### ISSUE TITLE
Update AlipaySDK to remove UIWebView

### ISSUE THREAD

**Issue by phyng** [0x5e/react-native-alipay#62]
> https://developer.apple.com/news/?id=12232019b
> The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

https://opendocs.alipay.com/open/54/104509
```
15.6.8
更新日期：2019-10-31

Android SDK

安全性优化。

解决应用在 Google Play 更新时，可能收到 加密模式 警告的问题。

iOS SDK

将 AlipaySDK 中的 UIWebView 更换为 WKWebView。

```

**Comment by pleasecmxx** [comment]
请问大佬有更新步骤吗？ @phyng

**Comment by phyng** [comment]
@pleasecmxx 我换了一个插件，参考这个 https://github.com/1035901787/react-native-s-alipay/issues/2 可以正常使用

**Comment by pleasecmxx** [comment]
好的，谢谢你 @phyng

**Comment by 0x5e** [comment]
@0x5e/react-native-alipay@0.2.7-beta
已更新，麻烦各位测试一下。工作原因，后面不会及时维护了，欢迎各位提交pr
@phyng @pleasecmxx

**Comment by song7788q** [comment]
ios13 没有回调，登录和支付成功都没有回调，有遇到的么？升级到@0x5e/react-native-alipay@0.2.7-beta 也没有回调
