### ISSUE TITLE
[Android] Error:(14) error: unknown element <activity> found.

### ISSUE THREAD

**Issue by django-wong** [0x5e/react-native-alipay#7]
Android Build之后，app/build/intermediates/manifests/full/debug/AndroidManifest.xml文件：

这两个activity似乎出现在错误的地方
```
    <activity
        android:name="com.alipay.sdk.app.H5PayActivity"
        android:configChanges="orientation|keyboardHidden|navigation|screenSize"
        android:exported="false"
        android:screenOrientation="behind"
        android:windowSoftInputMode="adjustResize|stateHidden" >
    </activity>
    <activity
        android:name="com.alipay.sdk.app.H5AuthActivity"
        android:configChanges="orientation|keyboardHidden|navigation"
        android:exported="false"
        android:screenOrientation="behind"
        android:windowSoftInputMode="adjustResize|stateHidden" >
    </activity>
```
完整的文件内容：
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.cagestsapp"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

    <activity
        android:name="com.alipay.sdk.app.H5PayActivity"
        android:configChanges="orientation|keyboardHidden|navigation|screenSize"
        android:exported="false"
        android:screenOrientation="behind"
        android:windowSoftInputMode="adjustResize|stateHidden" >
    </activity>
    <activity
        android:name="com.alipay.sdk.app.H5AuthActivity"
        android:configChanges="orientation|keyboardHidden|navigation"
        android:exported="false"
        android:screenOrientation="behind"
        android:windowSoftInputMode="adjustResize|stateHidden" >
    </activity>

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <application
        android:name="com.cagestsapp.MainApplication"
        android:allowBackup="true"
        android:debuggable="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name="com.cagestsapp.MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

**Comment by 0x5e** [comment]
这份文件完整吗，正常的应该是manifest为跟节点才对吧

**Comment by django-wong** [comment]
对，我没有复制xml和manifest节点
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.cagestsapp"
    android:versionCode="1"
    android:versionName="1.0" >
    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

    <activity
        android:name="com.alipay.sdk.app.H5PayActivity"
        android:configChanges="orientation|keyboardHidden|navigation|screenSize"
        android:exported="false"
        android:screenOrientation="behind"
        android:windowSoftInputMode="adjustResize|stateHidden" >
    </activity>
    <activity
        android:name="com.alipay.sdk.app.H5AuthActivity"
        android:configChanges="orientation|keyboardHidden|navigation"
        android:exported="false"
        android:screenOrientation="behind"
        android:windowSoftInputMode="adjustResize|stateHidden" >
    </activity>

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <application
        android:name="com.cagestsapp.MainApplication"
        android:allowBackup="true"
        android:debuggable="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name="com.cagestsapp.MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>
</manifest>
```

**Comment by django-wong** [comment]
我把`node_modules/@0x5e/react-native-alipay/android/src/main/AndroidManifest.xml`这个文件中的两个activity节点**剪切**到`android/app/src/main/AndroidManifest.xml` 的 `application`节点就好了。

没开发过Android，不确定这样有没有别的隐患，而且显然每次更新npm包都需要再操作一遍。

**Comment by 0x5e** [comment]
你的gradle版本是多少，是用android studio在编译吗？
另外有没有用到别的三方rn库，我这个库的包名应该改一下的，com.reactlibrary不知道是不是这个产生冲突了

**Comment by django-wong** [comment]
用的是gradle3.0.1，Android Studio版本也是3.0.1
全局搜了一下，`com.reactlibrary `这个名字只有`0x5e/react-native-alipay`在用。
用的其他包有：
"@shoutem/ui": "^0.23.4"
"mobx-react": "^4.3.5"
"react-native-elements": "^0.19.0"
"react-native-i18n": "^2.0.10"
"react-native-qrcode-svg": "^5.0.6"
"react-native-storage": "^0.2.2"
"react-native-svg": "^6.0.1-rc.3"
"react-native-vector-icons": "^4.5.0"
"react-native-wechat": "^1.9.9"

**Comment by 0x5e** [comment]
用2.x的gradle试一下呢？我现在电脑里没有安卓环境。。

**Comment by wohaiwo** [comment]
### react-native-alipay sdk 问题
  - ios 出现 duplicate symbol _OBJC_METACLASS_$\_UTDIDStringUtils in: libAlipaySDK.a
    34 duplicate symbols for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    去 蚂蚁金服官网 [蚂蚁金服SDK下载](https://docs.open.alipay.com/54/104509/) 下载 sdk (适用于集成了百川 sdk，出现 UTDID 冲突)的版本 放到 node_modules => @0x5e/react-native-alipay 替换 ios sdk 文件
- android 出现 <activity> not found 问题
  在 node_modules => @0x5e/react-native-alipay android - AndroidManifest.xml 中 将 `<activity>` 包裹于 `<application>`下面

**Comment by 0x5e** [comment]
@wohaiwo 问题一和 #9 类似，有人需要UTDID版本，有人需要无UTDID版本，暂无两全方案；
问题二，欢迎提交PR

**Comment by zacksleo** [comment]
https://stackoverflow.com/questions/46948498/android-studio-3-0-manifest-error-unknown-element-action-found

看样子是 activity 节点所在位置不对

**Comment by zacksleo** [comment]
```bash
Download https://jcenter.bintray.com/com/tencent/mm/opensdk/wechat-sdk-android-without-mta/maven-metadata.xml
Download https://jcenter.bintray.com/com/tencent/mm/opensdk/wechat-sdk-android-without-mta/5.1.6/wechat-sdk-android-without-mta-5.1.6.pom
:react-native-gesture-handler:compileReleaseAidl
:react-native-picker:compileReleaseAidl
:react-native-webview:compileReleaseAidl
:react-native-wechat:compileReleaseAidl
:app:compileReleaseAidl
:react-native-gesture-handler:packageReleaseRenderscript NO-SOURCE
:react-native-picker:packageReleaseRenderscript NO-SOURCE
:react-native-webview:packageReleaseRenderscript NO-SOURCE
:react-native-wechat:packageReleaseRenderscript NO-SOURCE
:app:compileReleaseRenderscript
:app:checkReleaseManifest
:app:generateReleaseBuildConfig
:app:prepareLintJar UP-TO-DATE
:app:mainApkListPersistenceRelease
:app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
fs.js:1384
    throw error;
    ^

Error: watch /builds/moguyun/app/lipstick/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4/samples/native-binaries/tool-chains/src/main/cpp ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at NodeWatcher.watchdir (/builds/moguyun/app/lipstick/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (/builds/moguyun/app/lipstick/node_modules/sane/src/common.js:116:12)
    at emitTwo (events.js:126:13)
    at Walker.emit (events.js:214:7)
    at /builds/moguyun/app/lipstick/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/builds/moguyun/app/lipstick/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 34s
46 actionable tasks: 44 executed, 2 up-to-date
ERROR: Job failed: exit code 1
```

试了一下，出现错误，这是什么原因呢？
